### ISSUE TITLE
Add a new variable

### ISSUE THREAD

**Issue by mpaglia0** [johanvergeer/pelican-series#1]
Hi!
Very nice and useful plugin.
Is it possible to add a new variable (let's call it <article.series.first>) that can be used to trigger the FIRST article of a serie?
This could be useful in case someone (I am trying to do this) don't like very much to use a separate index but will prefer to put buttons at the bottom of each article.
I have obtained very quickly a NEXT ARTICLE and PREVIOUS ARTICLE buttons but cannot understand how to place a GO TO THE FIRST ARTICLE one...
Thanks!
![plugin_series](https://user-images.githubusercontent.com/21242068/113118467-c7d93e00-920f-11eb-9fc0-d0cdd127058b.jpg)

**Comment by johanvergeer** [comment]
Hi @mpaglia0 ,

I've just added a `first` and `last` key to the series data of each article. Could you give that a try?

**Comment by mpaglia0** [comment]
I will give it a try as soon as I can put hands on my PC and will let you know.
Thank you!

**Comment by mpaglia0** [comment]
``article.series.next.url`` and ``article.series.previous.url`` works perfectly but if I set ``article.series.first.url`` I obtain the following error from jinja2:
> jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'first'

**Comment by mpaglia0** [comment]
My complete piece of code:

```html
<ul class="pager">
        <li class="next">
            {% if article.series.next %}
            <a href="{{ SITEURL }}/{{ article.series.next.url }}">{{ 'Next part'|gettext(DEFAULT_LANG) }} &rarr;</a>
            {% endif %}
            {% if article.series.index != 1 %}
            <a href="{{ SITEURL }}/{{ article.series.first.url }}">{{ 'Go to the beginning'|gettext(DEFAULT_LANG) }}</a>
            {% endif %}
            {% if article.series.previous %}
            <a href="{{ SITEURL }}/{{ article.series.previous.url }}"> &larr; {{ 'Previous part'|gettext(DEFAULT_LANG) }}</a>
            {% endif %}
        </li>
    </ul>
```

**Comment by johanvergeer** [comment]
Could you check whether you're using the correct version of the plugin with `pip show pelican-series-plugin`, which should be `1.1.1`?

**Comment by mpaglia0** [comment]
1.0.2

**Comment by mpaglia0** [comment]
If I try to force installation of 1.1.1 pip says
```
ERROR: Could not find a version that satisfies the requirement pelican-series-plugin==1.1.1
ERROR: No matching distribution found for pelican-series-plugin==1.1.1
```

**Comment by johanvergeer** [comment]
I just tried to install version `1.1.1` and it works. 

Which version of Python are you running your Pelican project on?

**Comment by mpaglia0** [comment]
3.6.12 on Suse Leap 15.2

**Comment by johanvergeer** [comment]
I updated the required Python versions to Python 3.8 and 3.9. So when you upgrade, you should be good to go.

**Comment by mpaglia0** [comment]
@johanvergeer 
Works as expected!

![screenshot](https://user-images.githubusercontent.com/21242068/113486131-7059fd00-94b1-11eb-804a-c54fd2ea6540.jpg)

Thank you indeed for your time and your patience.
Have a relaxing Easter.

**Comment by johanvergeer** [comment]
You're welcome, @mpaglia0.

Thank you for your feature suggestion. Happy easter to you too.
